Repository gathering/wannabe, pull requests merged in 2020-10, with the labels that each got.

#31 Add crew name validation
  app/Controller/CrewAdminController.php
  app/Controller/CrewController.php
  app/Model/Crew.php
  app/View/Elements/wikipage.ctp
Labels: enhancement, hacktoberfest-accepted

#34 Handle soft-deleted/disabled users
  README.md
  app/Console/Command/UserShell.php
  app/Controller/Component/AuthComponent.php
  app/Controller/LoginController.php
  app/Controller/ProfileController.php
  app/Model/User.php
  app/View/Profile/view.ctp
Labels: enhancement

#61 Adding support for other genders than male and female
  app/Controller/ProfileController.php
  app/Locale/default.po
  app/Locale/eng/LC_MESSAGES/default.po
  app/Locale/nob/LC_MESSAGES/default.po
  sql/dev.sql
Labels: hacktoberfest-accepted

#63 Migrate away all remaining md5 password hashes
  migrate/.migrations/20201019173710_wipe_passwords_with_insecure_hash.migration
Labels: hacktoberfest-accepted

#64 Enable editing of FrontNews items regardless of user language
  app/Controller/FrontNewsManagerController.php
  app/Model/FrontNews.php
  app/View/FrontNewsManager/add.ctp
  app/View/FrontNewsManager/edit.ctp
  app/View/FrontNewsManager/index.ctp
Labels: hacktoberfest-accepted

#65 Signed user profile picture urls
  Dockerfile_nginx
  INSTALL.md
  app/Config/bootstrap.php
  app/Plugin/Cfad/View/Member/index.ctp
  app/View/Crew/list-extended.ctp
  app/View/Crew/view.ctp
  app/View/Elements/profile.ctp
  app/View/Helper/WbHelper.php
  app/View/Home/index-old.ctp
  app/View/Home/index.ctp
  app/View/Profile/picture-accepted.ctp
  app/View/Profile/picture.ctp
  app/View/Profile/view.ctp
  build/wannabe-nginx.conf
  docker-compose.dev.yml
Labels: hacktoberfest-accepted

#66 Add shared privacy filter utility
  app/Controller/Component/AclComponent.php
  app/Controller/CrewController.php
  app/Controller/ProfileController.php
  app/Plugin/Api/Controller/ApiAppController.php
  app/View/Crew/list-extended.ctp
  app/View/Crew/view.ctp
  app/View/Profile/view.ctp
Labels: hacktoberfest-accepted
